### ISSUE TITLE
Port to JavaScript (jtskit-js)

### ISSUE THREAD

**Issue by pwalsh** [okfn/jtskit-py#4]
Do an exact port of this API to JavaScript as jtskit-js.

Keep the py/js versions consistent as references for the JTS Spec.

Thought: If **I** end up doing this, I'd prefer to use ES6 classes so that the code of each version is fairly consistent to read (easier to achieve API parity), and create the dist version with es6to5.

This could then be used in https://github.com/okfn/json-table-schema-validator to extend its coverage of the JTS spec.

**Comment by jpatel3** [comment]
@pwalsh or other way to do it is in typescript to make it even more flexible.

**Comment by pwalsh** [comment]
This work will begin here: https://github.com/okfn/jtskit-js

Closing this ticket.
